apiVersion: v1
kind: Service
metadata:
  name: goapp
  namespace: simpleservice
  labels:
    app: goapp
spec:
  type: NodePort
  ports:
   - port: 8000
     targetPort: 8000
  selector:
    app: goapp

