apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: simpleservice
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
   - port: 5432
     targetPort: 5432
  selector:
     app: postgresql
