apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: simpleservice
spec:
  serviceName: "postgresql"
  selector:
   matchLabels:
      app: postgresql
      tier: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
        tier: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim-01
